version: "3"
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: Root-Passwort
      MYSQL_DATABASE: DB-Name
      MYSQL_USER: User
      MYSQL_PASSWORD: User-Passwort
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/mnt/usb_hermes/volumes/mariadb-data/_data
    networks:
      - edge
  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - nodered-data:/mnt/usb_hermes/volumes/smartmeter_nodered-data/_data
    networks:
      - edge
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/mnt/usb_hermes/volumes/smartmeter_grafana-data/_data
    networks:
      - edge
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: unless-stopped
    environment:
      INFLUXDB_DB: smartmeter
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: Admin
      INFLUXDB_ADMIN_PASSWORD: Admin-Passwort
      INFLUXDB_USER: User
      INFLUXDB_USER_PASSWORD: User-Passwort
    ports:
      - "8082:8082"
      - "8086:8086"
      - "8089:8089"
    volumes:
      - influx-data:/mnt/usb_hermes/volumes/smartmeter_influx-data/_data
    networks:
      - edge
  mosquitto:
    image: eclipse-mosquitto:1.6.14
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9005:9005"
    volumes:
      - mosquitto-log:/mnt/usb_hermes/volumes/smartmeter_mosquitto-log/_data
      - mosquitto-data:/mnt/usb_hermes/volumes/smartmeter_mosquitto-data/_data
    networks:
      - edge
  python:
    build: ./python
    container_name: python
    # mount USB
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
    networks:
      - edge
  #Create internal link network for Containers
networks:
  edge: #Create Volumes for persistent Storage
volumes:
  grafana-data:
    external: true
  nodered-data:
    external: true
  influx-data:
    external: true
  mosquitto-log:
    external: true
  mosquitto-data:
    external: true
  mariadb:
    external: true
